// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    { type: 'doc', id: 'index', label: 'Home' },
    { type: 'doc', id: 'getting-started', label: 'Getting Started' },
    { type: 'doc', id: 'workflows', label: 'Workflows' },
    { type: 'doc', id: 'configuration', label: 'Configuration' },
    { type: 'doc', id: 'security', label: 'Security' },
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'Agentics Workflows',
      items: [
        { type: 'autogenerated', dirName: 'agentics-docs' },
      ],
    },
  ],
};

export default sidebars;
