name: Compile workflows with latest gh-aw release

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install-gh-aw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install gh-aw
        run: gh extension install github/gh-aw
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify gh-aw installation
        run: gh aw --version
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile workflows in .github/workflows
        run: gh aw compile --verbose
        env: 
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
